### PR TITLE
add nightclub & shadowban

### PR DESCRIPTION
**Pull request by BandiDaHero**

### CODE REVIEW

**Comment by TheFenderStory** [comment]
hahahahahahahahaha ha    ha .....ha FUCK YOU BANDI. Your commits literally crashed the fuck out of us. Profile was causing an enormous amount of crashes because of the changes you made, not to mention deleting the whole fucking money systtem without my permission. ARE YOU kidding ME? Sparky didn't know better when she merged the pull, but had i seen it first, i would have laughed at you and denied it, which i am gonna do anyway. Thanks for the help but nine and i are gonna be handling shit from here on out dude/

**Comment by BandiDaHero** [comment]
:]

**Comment by naten2006** [comment]
Are you serious, Bandi?

**Comment by BandiDaHero** [comment]
nah it was a trollface (literally not sarcasm) i already pmed fender on everything i didn't do it on purpose

**Pull request closed without merging**
